// This file was auto-generated by prisma-generator-typescript-interfaces

export type ProcessingStatus = "PENDING" | "PROCESSING" | "SAVING" | "COMPLETED" | "FAILED";

export type VerificationStatus = "UNVERIFIED" | "VERIFIED";

export type InvoiceType = "ACCOUNTS_PAYABLE" | "ACCOUNTS_RECEIVABLE";

export type PaymentStatus = "PAID" | "UNPAID";

export type Role = "USER" | "ADMIN";

export type Invoice = {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  fileName: string;
  originalFileName: string;
  mimeType: string;
  filePath: string;
  currentProcessingStatus: ProcessingStatus;
  verificationStatus: VerificationStatus;
  projectName: string | null;
  invoiceType: InvoiceType | null;
  paymentStatus: PaymentStatus;
  CustomerName: string | null;
  CustomerId: string | null;
  PurchaseOrder: string | null;
  InvoiceId: string | null;
  InvoiceDate: Date | null;
  DueDate: Date | null;
  VendorName: string | null;
  VendorAddress: string | null;
  VendorAddressRecipient: string | null;
  CustomerAddress: string | null;
  CustomerAddressRecipient: string | null;
  BillingAddress: string | null;
  BillingAddressRecipient: string | null;
  ShippingAddress: string | null;
  ShippingAddressRecipient: string | null;
  SubTotal: string | null;
  TotalDiscount: string | null;
  TotalTax: string | null;
  InvoiceTotal: number | null;
  AmountDue: string | null;
  PreviousUnpaidBalance: string | null;
  RemittanceAddress: string | null;
  RemittanceAddressRecipient: string | null;
  ServiceAddress: string | null;
  ServiceAddressRecipient: string | null;
  ServiceStartDate: string | null;
  ServiceEndDate: string | null;
  VendorTaxId: string | null;
  CustomerTaxId: string | null;
  PaymentTerm: string | null;
  user?: User;
  userId: number;
};

export type User = {
  id: number;
  firstName: string;
  username: string;
  password: string;
  role: Role;
  createdAt: Date;
  refreshToken: string | null;
  invoices?: Invoice[];
};
